resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: sql-env
  literals:
    - ACCEPT_EULA=Y

secretGenerator:
- name: sql-secrets
  envs:
  - .sql.secrets
