name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AspireEnvironment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image api
        uses: docker/build-push-action@v2
        with:
          file: ./DotnetAspireExample.ApiService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dotnetapsireapiservice:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: ./DotnetAspireExample.Web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dotnetapsireweb:latest
